//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class client
    {
        public client()
        {
            this.offices = new ObservableCollection<office>();
            name = "Jaœ pukacz";
        }
    
        public int clientId { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public string contact_person_name { get; set; }
        public string mail { get; set; }
        public string tel { get; set; }
        public string NIP { get; set; }
        public string comments { get; set; }
    
        public virtual ObservableCollection<office> offices { get; set; }
    }
}
