//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class model_of_gauges
    {
        public model_of_gauges()
        {
            this.gauges = new ObservableCollection<gauge>();
            this.calibrators_model_of_gauges = new ObservableCollection<calibrators_model_of_gauges>();
        }
    
        public int model_of_gaugeId { get; set; }
        public string manufacturer_name { get; set; }
        public string model { get; set; }
        public int usage_id { get; set; }
        public int type_id { get; set; }
    
        public virtual ObservableCollection<gauge> gauges { get; set; }
        public virtual type type { get; set; }
        public virtual usage usage { get; set; }
        public virtual ObservableCollection<calibrators_model_of_gauges> calibrators_model_of_gauges { get; set; }
    }
}
