//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class laboratoryEntities : DbContext
    {
        public laboratoryEntities()
            : base("name=laboratoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificate> certificates { get; set; }
        public virtual DbSet<Client> clients { get; set; }
        public virtual DbSet<Gauge> gauges { get; set; }
        public virtual DbSet<Office> offices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type> types { get; set; }
        public virtual DbSet<Usage> usages { get; set; }
    
       
    }
}
