//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;

    public partial class office : ViewModel.MenuItem
    {
        public office()
        {
            this.gauges = new ObservableCollection<gauge>();
        }
    
        public int officeId { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public string contact_person_name { get; set; }
        public string mail { get; set; }
        public string tel { get; set; }
        public string is_default { get; set; }
        public int client_id { get; set; }
    
        public virtual client client { get; set; }
        public virtual ObservableCollection<gauge> gauges { get; set; }

        protected override string displayImagePath
        {
            get
            {
                return @"C:\Users\daniel\Documents\Visual Studio 2013\Projects\LaboratoryApp\LaboratoryApp\icon\office-building-icon.png";
            }
        }

        protected override string nameOfItem
        {
            get
            {
                return base.nameOfItem;
            }
            set
            {
                base.nameOfItem = value;
                OnPropertyChanged("nameOfItem");
            }
        }

        protected override ObservableCollection<ViewModel.MenuItem> children
        {
            get
            {
                return base.children;
            }
            set
            {
                base.children = value;
                OnPropertyChanged("children");
            }
        }
    }
}
