//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("offices")]
    public partial class Office
    {
        public int officeId { get; set; }
        public string name { get; set; }
        public string adress { get; set; }
        public string contact_person_name { get; set; }
        public string mail { get; set; }
        public string tel { get; set; }
        public string is_default { get; set; }
        public int client_id { get; set; }
    
        public virtual Client client { get; set; }
    }
}
