//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class product
    {
        public int productId { get; set; }
        public int serial_number { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> office_id { get; set; }
        public Nullable<int> gauge_id { get; set; }
    
        public virtual gauge gauge { get; set; }
        public virtual office office { get; set; }
    }
}
