//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("types")]
    public partial class Type
    {
        public Type()
        {
            this.gauges = new ObservableCollection<Gauge>();
        }
    
        public int typeId { get; set; }
        public string name { get; set; }
    
        public virtual ObservableCollection<Gauge> gauges { get; set; }
    }
}
