//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class type
    {
        public type()
        {
            this.model_of_gauges = new ObservableCollection<model_of_gauges>();
        }
    
        public int typeId { get; set; }
        public string name { get; set; }
    
        public virtual ObservableCollection<model_of_gauges> model_of_gauges { get; set; }
    }
}
