//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaboratoryApp
{
    using System;
    using System.Collections.ObjectModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class usage
    {
        public usage()
        {
            this.gauges = new ObservableCollection<gauge>();
        }
    
        public int usageId { get; set; }
        public string description { get; set; }
    
        public virtual ObservableCollection<gauge> gauges { get; set; }
    }
}
